# Generated by Django 3.1.2 on 2021-01-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_post_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uname',
            field=models.CharField(max_length=150),
        ),
    ]
