# Generated by Django 3.1.2 on 2021-01-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
